CONTIKI_PROJECT = sky-transceiver
all: $(CONTIKI_PROJECT) $(CONTIKI_PROJECT).ihex

CONTIKI = ../..

TARGET = sky

MAKE_MAC = MAKE_MAC_CSMA
MAKE_NET = MAKE_NET_NULLNET
include $(CONTIKI)/Makefile.include

